env:
  - "RAILS_VERSION=3.2.15"
  - "RAILS_VERSION=3.2.19"
  - "RAILS_VERSION=4.0.0"
  - "RAILS_VERSION=4.1.0"
  - "RAILS_VERSION=4.2.0"
  - "RAILS_VERSION=master"
 
rvm:
 - 1.9.3
 - 2.0.0
 - jruby-19mode


matrix:
  allow_failures:
    - env: "RAILS_VERSION=master"
    - rvm: ruby-head
